### PR TITLE
Fix runner hanging, fix an error in thread handling, and serialize concurrent generator-runner invocations

### LINKED ISSUE #6804: ../datalad/support/tests/test_annexrepo.py::test_is_available[False]  is stalling in master
e.g. https://ci.appveyor.com/project/mih/datalad/builds/44082389/job/mw5l35ntiak9xmaa of https://github.com/datalad/datalad/pull/6803 :

```
PASSED
../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
```
but also came up in other scenarios recently in e.g. https://github.com/datalad/datalad/pull/6518#issuecomment-1171417710 

more hits from our logs archives which show that it is not a new problem
```
(git)smaug:/mnt/datasets/datalad/ci/logs/2022/07[master]git
$> git grep -B2 'No output has been received in the last' | grep ::test
01/cron/20220701T193907/797dde3/travis-14182-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
01/pr/6518/3496925/travis-14176-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
02/pr/6790/73d48cc/travis-14189-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
05/pr/6803/fcf849c/travis-14211-errored/1.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 

$> cd ../06

(git)smaug:/mnt/datasets/datalad/ci/logs/2022/06[master]git
$> git grep -B2 'No output has been received in the last' | grep ::test
03/cron/20220603T193647/173dc6f/travis-14100-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
08/pr/6690/ada1778/travis-14121-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
09/push/master/4d53077/travis-14129-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
10/cron/20220610T193717/029f839/travis-14136-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
10/cron/20220610T193717/029f839/travis-14136-errored/5.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
13/push/master/0654290/travis-14140-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
14/push/master/797dde3/travis-14144-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
17/cron/20220617T193730/797dde3/travis-14152-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
17/cron/20220617T193730/797dde3/travis-14152-errored/5.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
20/pr/6518/e1c9dda/travis-14155-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
23/pr/6518/67e5dc5/travis-14159-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
24/cron/20220624T193828/797dde3/travis-14163-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
24/cron/20220624T193828/797dde3/travis-14163-errored/5.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
29/pr/6518/e9aab74/travis-14171-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
30/pr/6518/3496925/travis-14176-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
30/pr/6518/e9aab74/travis-14171-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False]

(git)smaug:/mnt/datasets/datalad/ci/logs/2022/07[master]git
$> git grep -B2 'No output has been received in the last' | grep ::test
01/cron/20220701T193907/797dde3/travis-14182-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
01/pr/6518/3496925/travis-14176-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
02/pr/6790/73d48cc/travis-14189-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
05/pr/6803/fcf849c/travis-14211-errored/1.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
(dev3) 2 6154.....................................:Tue 05 Jul 2022 02:04:51 PM EDT:.
(git)smaug:/mnt/datasets/datalad/ci/logs/2022/07[master]git
$> cd ../06

(git)smaug:/mnt/datasets/datalad/ci/logs/2022/06[master]git
$> git grep -B2 'No output has been received in the last' | grep ::test
03/cron/20220603T193647/173dc6f/travis-14100-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
08/pr/6690/ada1778/travis-14121-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
09/push/master/4d53077/travis-14129-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
10/cron/20220610T193717/029f839/travis-14136-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
10/cron/20220610T193717/029f839/travis-14136-errored/5.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
13/push/master/0654290/travis-14140-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
14/push/master/797dde3/travis-14144-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
17/cron/20220617T193730/797dde3/travis-14152-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
17/cron/20220617T193730/797dde3/travis-14152-errored/5.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
20/pr/6518/e1c9dda/travis-14155-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
23/pr/6518/67e5dc5/travis-14159-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
24/cron/20220624T193828/797dde3/travis-14163-errored/16.txt-../datalad/local/tests/test_run_procedure.py::test_text2git 
24/cron/20220624T193828/797dde3/travis-14163-errored/5.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
29/pr/6518/e9aab74/travis-14171-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
30/pr/6518/3496925/travis-14176-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False] 
30/pr/6518/e9aab74/travis-14171-errored/4.txt-../datalad/support/tests/test_annexrepo.py::test_is_available[False]
```

and there were some timing out runs before May but we were not `-v` so not clear which test was to implicate.
It might as well be git-annex issue since we are testing against somewhat older git-annex in those I believe.

### LINKED ISSUE #7138: test_creatsubdatasets: RuntimeError: ThreadedRunner.run() was re-entered
spotted in the recent build on OSX using snapshot version of git-annex build:

https://github.com/datalad/datalad/actions/runs/3379647930/jobs/5611473605

```
>       assert_raises(IncompleteResultsError, list, ProducerConsumer(paths[::-1], create_, jobs=5))

../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/tests/test_parallel.py:129: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/parallel.py:265: in __iter__
    yield from self._iter_threads(self._jobs)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/parallel.py:417: in _iter_threads
    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/parallel.py:233: in shutdown
    raise exception
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/parallel.py:401: in _iter_threads
    done_useful |= self._pop_done_futures(lgr)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/parallel.py:463: in _pop_done_futures
    raise exception
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/concurrent/futures/thread.py:57: in run
    result = self.fn(*self.args, **self.kwargs)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/parallel.py:329: in consumer_worker
    for r in res:
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/interface/utils.py:452: in _execute_command_
    allkwargs):
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/interface/utils.py:619: in _process_results
    for res in results:
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/core/local/create.py:291: in __call__
    paths=[check_path.relative_to(parentds_path)])
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/gitrepo.py:2874: in status
    eval_submodule_state=eval_submodule_state)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/gitrepo.py:2997: in diffstatus
    from_state = self.get_content_info(paths=paths, ref=fr)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/support/gitrepo.py:2767: in get_content_info
    read_only=True)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/dataset/gitrepo.py:461: in call_git
    keep_ends=True))
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/dataset/gitrepo.py:522: in call_git_items_
    sep=sep):
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/dataset/gitrepo.py:355: in _generator_call_git
    for file_no, content in generator:
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/runner/gitrunner.py:305: in run_on_filelist_chunks_items_
    **kwargs):
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/runner/gitrunner.py:189: in _get_chunked_results
    **kwargs)
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/runner/runner.py:194: in run
    results_or_iterator = self.threaded_runner.run()
../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/runner/nonasyncrunner.py:320: in run
    return self._locked_run()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _locked_run(self) -> dict | _ResultGenerator:
        if self.generator is not None:
>           raise RuntimeError("ThreadedRunner.run() was re-entered")
E           RuntimeError: ThreadedRunner.run() was re-entered

../../../../hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/datalad/runner/nonasyncrunner.py:324: RuntimeError

---------- coverage: platform darwin, python 3.7.15-final-0 ----------
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
FAILED ../tests/test_parallel.py::test_creatsubdatasets - RuntimeError: ThreadedRunner.run() was re-entered
============ 1 failed, 392 passed, 35 skipped in 3114.32s (0:51:54) ============
```

and that exception was seen raised (test seems to fail or error also for other reasons in the past, so grepping for the exception)

```
(git)smaug:/mnt/datasets/datalad/ci/logs/2022[master]git
$> datalad foreach-dataset --o-s relpath git grep 'ThreadedRunner.run() was re-entered'                                      
06/02/pr/6737/60b6f94/appveyor-8048-failed/o7ip9u3udu7odsg6.txt:[00:15:51]     raise RuntimeError("ThreadedRunner.run() was re-entered")                                                                                                                           
06/02/pr/6737/60b6f94/appveyor-8048-failed/o7ip9u3udu7odsg6.txt:[00:15:51] RuntimeError: ThreadedRunner.run() was re-entered
06/02/pr/6737/abbf61b/appveyor-8049-failed/fla2okr02r6snseh.txt:[00:17:18]     raise RuntimeError("ThreadedRunner.run() was re-entered")
06/02/pr/6737/abbf61b/appveyor-8049-failed/fla2okr02r6snseh.txt:[00:17:18] RuntimeError: ThreadedRunner.run() was re-entered
06/03/pr/6737/81f8b2d/appveyor-8059-failed/61o073tsjurpnalc.txt:[00:14:43]     raise RuntimeError("ThreadedRunner.run() was re-entered")
06/03/pr/6737/81f8b2d/appveyor-8059-failed/61o073tsjurpnalc.txt:[00:14:43] RuntimeError: ThreadedRunner.run() was re-entered
06/03/pr/6737/a4519d8/github-Test on macOS-3326-failed/2_test (snapshot).txt:2022-06-03T09:42:09.4228590Z     raise RuntimeError("ThreadedRunner.run() was re-entered")
06/03/pr/6737/a4519d8/github-Test on macOS-3326-failed/2_test (snapshot).txt:2022-06-03T09:42:09.4228990Z RuntimeError: ThreadedRunner.run() was re-entered
06/03/pr/6737/a4519d8/github-Test on macOS-3326-failed/test (snapshot)/8_Run tests.txt:2022-06-03T09:42:09.4228590Z     raise RuntimeError("ThreadedRunner.run() was re-entered")
06/03/pr/6737/a4519d8/github-Test on macOS-3326-failed/test (snapshot)/8_Run tests.txt:2022-06-03T09:42:09.4228990Z RuntimeError: ThreadedRunner.run() was re-entered
06/03/pr/6740/d6f1cdd/appveyor-8060-failed/vf6voxcyv67lwaox.txt:[00:03:16]     raise RuntimeError("ThreadedRunner.run() was re-entered")
06/03/pr/6740/d6f1cdd/appveyor-8060-failed/vf6voxcyv67lwaox.txt:[00:03:16] RuntimeError: ThreadedRunner.run() was re-entered
09/19/push/maint/27c18e8/appveyor-8543-failed/4endjtn7v53adf2h.txt:[00:17:12] >           raise RuntimeError("ThreadedRunner.run() was re-entered")                                                                                                                
09/19/push/maint/27c18e8/appveyor-8543-failed/4endjtn7v53adf2h.txt:[00:17:12] E           RuntimeError: ThreadedRunner.run() was re-entered
09/19/push/maint/27c18e8/appveyor-8543-failed/4endjtn7v53adf2h.txt:[00:17:12] FAILED ../datalad/support/tests/test_parallel.py::test_creatsubdatasets - RuntimeError: ThreadedRunner.run() was re-entered
10/12/pr/7084/44d7557/appveyor-8646-failed/hsb8f27cmg1m57g0.txt:[00:19:56] >           raise RuntimeError("ThreadedRunner.run() was re-entered")                                                                                                                   
10/12/pr/7084/44d7557/appveyor-8646-failed/hsb8f27cmg1m57g0.txt:[00:19:56] E           RuntimeError: ThreadedRunner.run() was re-entered
10/12/pr/7084/44d7557/appveyor-8646-failed/hsb8f27cmg1m57g0.txt:[00:19:56] FAILED ../datalad/support/tests/test_parallel.py::test_creatsubdatasets - RuntimeError: ThreadedRunner.run() was re-entered
10/24/pr/7111/ca436bf/github-Test on macOS-3958-failed/1_test (brew).txt:2022-10-24T19:12:27.9900650Z >           raise RuntimeError("ThreadedRunner.run() was re-entered")
10/24/pr/7111/ca436bf/github-Test on macOS-3958-failed/1_test (brew).txt:2022-10-24T19:12:27.9901570Z E           RuntimeError: ThreadedRunner.run() was re-entered
10/24/pr/7111/ca436bf/github-Test on macOS-3958-failed/test (brew)/8_Run tests.txt:2022-10-24T19:12:27.9900650Z >           raise RuntimeError("ThreadedRunner.run() was re-entered")
10/24/pr/7111/ca436bf/github-Test on macOS-3958-failed/test (brew)/8_Run tests.txt:2022-10-24T19:12:27.9901560Z E           RuntimeError: ThreadedRunner.run() was re-entered
10/24/pr/UNK/ca436bf/github-Test on macOS-3958-failed/1_test (brew).txt:2022-10-24T19:12:27.9900650Z >           raise RuntimeError("ThreadedRunner.run() was re-entered")
10/24/pr/UNK/ca436bf/github-Test on macOS-3958-failed/1_test (brew).txt:2022-10-24T19:12:27.9901570Z E           RuntimeError: ThreadedRunner.run() was re-entered
10/24/pr/UNK/ca436bf/github-Test on macOS-3958-failed/test (brew)/8_Run tests.txt:2022-10-24T19:12:27.9900650Z >           raise RuntimeError("ThreadedRunner.run() was re-entered")
10/24/pr/UNK/ca436bf/github-Test on macOS-3958-failed/test (brew)/8_Run tests.txt:2022-10-24T19:12:27.9901560Z E           RuntimeError: ThreadedRunner.run() was re-entered
datalad foreach-dataset --o-s relpath git grep   57.95s user 48.87s system 461% cpu 23.163 total  
```

so happened on OSX but also on appveyor on debian/ubuntu:

```
$> datalad foreach-dataset --o-s relpath git grep -l 'ThreadedRunner.run() was re-entered' | grep -v macOS | xargs grep -e '## system' -A1 
06/02/pr/6737/60b6f94/appveyor-8048-failed/o7ip9u3udu7odsg6.txt:[00:02:38] ## system 
06/02/pr/6737/60b6f94/appveyor-8048-failed/o7ip9u3udu7odsg6.txt-[00:02:38]   - distribution: debian/bullseye/sid
--
06/02/pr/6737/abbf61b/appveyor-8049-failed/fla2okr02r6snseh.txt:[00:02:30] ## system 
06/02/pr/6737/abbf61b/appveyor-8049-failed/fla2okr02r6snseh.txt-[00:02:30]   - distribution: debian/bullseye/sid
--
06/03/pr/6737/81f8b2d/appveyor-8059-failed/61o073tsjurpnalc.txt:[00:02:54] ## system 
06/03/pr/6737/81f8b2d/appveyor-8059-failed/61o073tsjurpnalc.txt-[00:02:54]   - distribution: debian/bullseye/sid
--
06/03/pr/6740/d6f1cdd/appveyor-8060-failed/vf6voxcyv67lwaox.txt:[00:02:55] ## system 
06/03/pr/6740/d6f1cdd/appveyor-8060-failed/vf6voxcyv67lwaox.txt-[00:02:55]   - distribution: debian/bullseye/sid
--
09/19/push/maint/27c18e8/appveyor-8543-failed/4endjtn7v53adf2h.txt:[00:02:02] ## system 
09/19/push/maint/27c18e8/appveyor-8543-failed/4endjtn7v53adf2h.txt-[00:02:02]   - distribution: ubuntu/20.04/focal
--
10/12/pr/7084/44d7557/appveyor-8646-failed/hsb8f27cmg1m57g0.txt:[00:02:09] ## system 
10/12/pr/7084/44d7557/appveyor-8646-failed/hsb8f27cmg1m57g0.txt-[00:02:09]   - distribution: debian/bullseye/sid
datalad foreach-dataset --o-s relpath git grep -l   77.93s user 46.18s system 1042% cpu 11.904 total
grep --color=auto -d skip -v macOS  0.00s user 0.00s system 0% cpu 11.904 total
xargs grep -e '## system' -A1  0.01s user 0.00s system 0% cpu 11.909 total
```

edit: and it was on pythons 3.7.12, 3.7.13, and 3.8.10

### PR DESCRIPTION
**Pull request by christian-monch**
This PR fixes a number of issues.

The PR extends the number of concurrent runner-call scenarios beyond the current implementation, i.e. serialize synchronous (non-generator) `ThreadedRunner.run()`-calls. The scenarios now supported are:

1. Concurrently invoke `ThreadedRunner.run()` without generator, leading to serialization of invocations.
2. Concurrently invoke `ThreadedRunner.run()` with generator, leading to serialisation of invocations, i.e. later invocations return if the currently active generator is exhausted
3. Concurrently read from a generator returned by `ThreadedRunner.run()`. Any number of threads can call `send()` on a generator, results will be returned as soon as they are available. Which of the waiting threads is continued is non-deterministic. If the generator is exhausted, all threads will receive a `StopIteration`-exception.

The serialization should fix spurious test errors. Fixes #7138

In addition the PR fixes an error that could lead to hanging threads if `close()` or `del` is called on a `BatchedCommand`-instance. This should fix a number of hanging errors in tests that use the `@serve_path_via_http()` decorator. Fixes #6804

### CODE REVIEW

File: changelog.d/pr-7201.md [hunk 1]
```diff
@@ -0,0 +1,13 @@
+### 🚀 Enhancements and New Features
+
+- Enhance concurrent invocation behavior of `ThreadedRunner.run()`. If possible invocations are serialized instead of raising *re-enter* runtime errors. Deadlock situations are detected and runtime errors are raised instead of deadlocking.
+  Fixes [#7138](https://github.com/datalad/datalad/issues/7138) via
+  [PR #72ß1](https://github.com/datalad/datalad/pull/7201)
```
Comment (yarikoptic) [inline changelog.d/pr-7201.md:5]:
```suggestion
  [PR #7201](https://github.com/datalad/datalad/pull/7201)
```
?

File: datalad/runner/exception.py [hunk 2]
```diff
@@ -35,17 +35,14 @@ def __init__(self, cmd="", msg="", code=None, stdout="", stderr="", cwd=None,
...
-        )
+        from datalad.utils import ensure_unicode
         to_str = "{}: ".format(self.__class__.__name__)
         cmd = self.cmd
         if cmd:
             to_str += "'{}'".format(
                 # go for a compact, normal looking, properly quoted
                 # command rendering if the command is in list form
-                join_cmdline(cmd) if isinstance(cmd, list) else cmd
+                " ".join(cmd) if isinstance(cmd, list) else cmd
```
Comment (yarikoptic) [inline datalad/runner/exception.py:45]: why to not use `join_cmdline` here to ensure that command could be just copy/pasted to be ran?

File: datalad/cmd.py [hunk 3]
```diff
@@ -200,7 +205,7 @@ class SafeDelCloseMixin(object):
     def __del__(self):
         try:
             self.close()
-        except TypeError:
+        except (TypeError, ImportError):
```
Comment (yarikoptic) [inline datalad/cmd.py:208]: could you leave a comment with when `ImportError` (and `TypeError` if you remember) is expected to happen?  not clear to me why only those 2.

File: datalad/runner/nonasyncrunner.py [hunk 4]
```diff
@@ -85,14 +87,26 @@ def __init__(self,
...
-    def send(self, _):
+    def send(self, message):
+        with self.send_lock:
+            return self._locked_send(message)
+
+    def _locked_send(self, message):
+        if self.state == self.GeneratorState.initialized:
+            if message is not None:
+                raise RuntimeError(
+                    "sent non-None message to initialized generator "
```
Comment (yarikoptic) [inline datalad/runner/nonasyncrunner.py:103]: should it be

```suggestion
                    f"sent non-None message {message!r} to initialized generator "
```
to ease debugging etc or `message` could be too big here?

File: datalad/runner/tests/test_nonasyncrunner.py [hunk 5]
```diff
@@ -83,6 +89,31 @@ def __init__(self,
         GeneratorMixIn.__init__(self)
 
 
+class GenStdoutLines(GeneratorMixIn, StdOutCapture):
```
Comment (yarikoptic) [inline datalad/runner/tests/test_nonasyncrunner.py:92]: docstring describing its purpose might come handy

**Review by yarikoptic — COMMENTED** [review]
from the description -- magnificent. Thank you !  Left some minor comments

File: datalad/runner/exception.py (hunk 2 above)
Comment (christian-monch) [reply datalad/runner/exception.py:45]: Thx! Can't remember why that was changed, reverted the change

File: datalad/cmd.py (hunk 3 above)
Comment (christian-monch) [reply datalad/cmd.py:208]: Not sure about `TypeError`, the code existed before, but I saw `ImportError`, if `BatchedCommand`-instances are deleted when the python interpreter is exiting. Comment added.

File: datalad/runner/tests/test_nonasyncrunner.py (hunk 5 above)
Comment (christian-monch) [reply datalad/runner/tests/test_nonasyncrunner.py:92]: Done

Comment (christian-monch) [reply datalad/runner/tests/test_nonasyncrunner.py:92]: Done

File: datalad/runner/exception.py (hunk 2 above)
Comment (christian-monch) [reply datalad/runner/exception.py]: Thx for catching that. Not sure why I changed it, but it is restored to usage of `join_cmdline`.

**Review by yarikoptic — APPROVED** [review]
Just left one typo fix suggestion. Glad to see new tests! Thank you!

**Comment by christian-monch** [comment]
> Just left one typo fix suggestion. Glad to see new tests! Thank you!

NP. You are welcome :-)

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.10`](https://github.com/datalad/datalad/releases/tag/0.17.10)
