### PR TITLE
BF: handle uninstalled subdatasets more gracefully

### LINKED ISSUE #7429: create-sibling-gitlab --recursive stumbles on uninstalled subds
In a dataset hierarchy with a yet uninstalled dataset, a recursive create-sibling-gitlab encounters an error:
```
~/my-webdav-clone master
❯ datalad create-sibling-gitlab -d . --recursive -s 'my-gitlab-sibling2' --layout flat
create_sibling_gitlab(ok): . (dataset) [sibling repository 'my-gitlab-sibling2' created at https://gitlab.com/datalad-fdm/hello]
configure-sibling(ok): . (sibling)
[ERROR  ] 'NoneType' object is not iterable 

```

This error is seemingly resolved when the subdataset is installed.

### PR DESCRIPTION
**Pull request by adswa**
Previously, an uninstalled subdataset would catch create-sibling-gitlab
off-guard, as if no path was given, its error handling would try to
iterate over a none-type object.
This change accounts for this possibility, and makes create-sibling-gitlab
handle this situation a bit more graceful and with better messaging.
Fixes #7429"

### CODE REVIEW

**Comment by yarikoptic** [comment]
I think it could go against `maint`.  
Having a test  would have been nice.
Changelog should be adjusted to note that this is create-sibling-gitlab specific, not some general handling.

File: changelog.d/pr-7430.md [hunk 1]
```diff
@@ -0,0 +1,3 @@
+### 🐛 Bug Fixes
+
+- BF: handle uninstalled subdatasets more gracefully.  [PR #7430](https://github.com/datalad/datalad/pull/7430) (by [@adswa](https://github.com/adswa))
```
Comment (adswa) [inline changelog.d/pr-7430.md:3]:
```suggestion
- BF: create-sibling-gitlab used to raise a TypeError when attempting a recursive operation in a dataset with uninstalled subdatasets. It now raises an impossible result instead.  [PR #7430](https://github.com/datalad/datalad/pull/7430) (by [@adswa](https://github.com/adswa))
```

**Comment by yarikoptic** [comment]
Looks good. Let's proceed!

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.19.3`](https://github.com/datalad/datalad/releases/tag/0.19.3)
