### PR TITLE
BF(TST): use older python 3.8 in testing nose utils

### LINKED ISSUE #7259: Nose tests action fails
The "old nose tests" Github action currently fails due to installation issues (reported version confllicts). Example here: https://github.com/datalad/datalad/actions/runs/3925056499/jobs/6709718821

We need to either fix it or consider disabling (do we still need this?)

### PR DESCRIPTION
**Pull request by yarikoptic**
New one 3.10 causes installation problems since likely simply no longer maintained/compatible. For the sake of it, fix it to test against 3.8 and in another PR against master we should deprecate/remove nose parts entirely

Closes #7259

### CODE REVIEW

File: changelog.d/pr-7260.md [hunk 1]
```diff
@@ -0,0 +1,3 @@
+### 🧪 Tests
+
+- BF(TST): use older python 3.8 in testing nose utils.  Fixes [#7259](https://github.com/datalad/datalad/issues/7259) via [PR #7260](https://github.com/datalad/datalad/pull/7260) (by [@yarikoptic](https://github.com/yarikoptic))
```
Comment (yarikoptic) [inline changelog.d/pr-7260.md:3]:
```suggestion
- Use older python 3.8 in testing nose utils in github-action test-nose.  Fixes [#7259](https://github.com/datalad/datalad/issues/7259) via [PR #7260](https://github.com/datalad/datalad/pull/7260) (by [@yarikoptic](https://github.com/yarikoptic))
```

**Comment by yarikoptic** [comment]
overall -- seems to be working, so I will merge since the only relevant "Test old nose code / test (pull_request) " passed and I just added the changelog snippet.

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.18.2`](https://github.com/datalad/datalad/releases/tag/0.18.2)
