### PR TITLE
BF: don't write output from within sshrun

### LINKED ISSUE #6599: Flaky SSH cloning failure in tests
Extracted from https://github.com/datalad/datalad/pull/6550#issuecomment-1073024568:

This only happens on AppVeyor (macOS again):

```
======================================================================
ERROR: datalad.core.distributed.tests.test_clone.test_ria_postclonecfg('ssh://datalad-test:/Users/appveyor/DLTMP/datalad_temp_ix8umpb9', '07c27167-6fef-443c-bbb7-3eec35daddc3')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/appveyor/projects/datalad/datalad/tests/utils.py", line 288, in _wrap_skip_ssh
    return func(*args, **kwargs)
  File "/Users/appveyor/projects/datalad/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/appveyor/projects/datalad/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/appveyor/projects/datalad/datalad/core/distributed/tests/test_clone.py", line 958, in _test_ria_postclonecfg
    riaclone = clone('ria+{}#{}'.format(url, dsid), clone_path)
  File "/Users/appveyor/projects/datalad/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/Users/appveyor/projects/datalad/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/Users/appveyor/projects/datalad/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'install',
  'message': ('Failed to clone from any candidate source URL. Encountered '
              'errors per each url were:\n'
              '- %s',
              'ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_ix8umpb9/07c/27167-6fef-443c-bbb7-3eec35daddc3\n'
              "  CommandError: 'git -c diff.ignoreSubmodules=none clone "
              '--progress '
              'ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_ix8umpb9/07c/27167-6fef-443c-bbb7-3eec35daddc3 '
              "/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgw5zk_49p' "
              "failed with exitcode 128 [err: 'Cloning into "
              "'/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgw5zk_49p'...\n"
              '\r'
              'remote: Total 37 (delta 7), reused 0 (delta 0)        \n'
              "fatal: remote transport reported error']"),
  'path': '/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgw5zk_49p',
  'source_url': 'ria+ssh://datalad-test:/Users/appveyor/DLTMP/datalad_temp_ix8umpb9#07c27167-6fef-443c-bbb7-3eec35daddc3',
  'status': 'error',
  'type': 'dataset'}]
```

This seems flaky. Logging into that AppVeyor build, showed, that this happens at different spots in this test.
Sometimes this clone seems to work out fine but then the subsequent `get` on a subdataset fails the same way.
So, currently the failure happens at line 958 in `test_clone.py` and on previous run (exact same commit) it only failed at line 1017.
Moreover, this should not be the only test where we clone from RIA via SSH. Not clear to me yet, how this is one is different.

Looking into this, I am seeing a Broken Pipe Error:
```
[DEBUG] ...>runner:192  Finished ['ssh', '-o', 'ControlPath=/Users/appveyor/Library/Caches/datalad/sockets/fb3f4327', '-o', 'SendEnv=GIT_PROTOCOL', 'datalad-test', "git-upload-pack '/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_vlst5whp/376/1c829-d43c-420a-95fb-4467944477c4'"] with status 0 
[ERROR] ...>main:136,185  [Errno 32] Broken pipe (BrokenPipeError) 
fatal: remote transport reported error']
```

And `git-upload-pack` seems a bit off indeed:

```
appveyor$ git-upload-pack '/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_vlst5whp/376/1c829-d43c-420a-95fb-4467944477c4'
010d74b31e4b1f6a81373783c6520507909436ca0f3b HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed symref=HEAD:refs/heads/dl-test-branch object-format=sha1 agent=git/2.35.1
004774b31e4b1f6a81373783c6520507909436ca0f3b refs/heads/dl-test-branch
0000
```
*hanging at this point*

And, of course, there's no problem running this right afterwards:
```
appveyor$ datalad clone "ria+ssh://datalad-test/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_vlst5whp#3761c829-d43c-420a-95fb-4467944477c4" test5                                                                 
Clone attempt:   0%|                                                                                                                                                                                                              | 0.00/1.00 [00:00<?, ? Candidate locations/s]@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:b7Q9hN2pEJGEvu/BlO2GUD/EV+H/xlmDqx7oCUosGbg.
Please contact your system administrator.
Add correct host key in /Users/appveyor/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/appveyor/.ssh/known_hosts:154
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
install(ok): /Users/appveyor/projects/test5 (dataset) 
```

### LINKED ISSUE #7078: test_get_subdataset_direct_fetch is flaky on OSX on appveyor
Failed in https://github.com/datalad/datalad/pull/7066#issuecomment-1268609480 and then later in other runs (con/tributing setup is waiting for github to get fixed, do not have recent fetches). Example from https://ci.appveyor.com/project/mih/datalad/builds/45005458/job/3v4wb1e356gxc3lq

```
test_get_subdataset_direct_fetch _______________________________________________________________________________________________________
[gw0] darwin -- Python 3.8.12 /Users/appveyor/venv3.8.12/bin/python
path = PosixPath('/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk')
    @skip_if_adjusted_branch
    @slow  # ~12s
    @skip_if_on_windows
    @skip_ssh
    @with_tempfile(mkdir=True)
    def test_get_subdataset_direct_fetch(path=None):
        path = Path(path)
        origin = Dataset(path / "origin").create()
        for sub in ["s0", "s1"]:
            sds = origin.create(origin.pathobj / sub)
            sds.repo.commit(msg="another commit", options=["--allow-empty"])
        origin.save()
        s0 = Dataset(origin.pathobj / "s0")
        s1 = Dataset(origin.pathobj / "s1")
        # Abandon the recorded commit so that it needs to be brought down by a
        # direct fetch.
        s0.repo.call_git(["reset", "--hard", "HEAD~"])
        s1.repo.call_git(["reset", "--hard", "HEAD~"])
    
        # Tweak the configuration of s0 to make the direct fetch fail.
        # Disallow direct oid fetch (default).
        s0.repo.config.set("uploadpack.allowAnySHA1InWant", "false",
                           scope="local")
        # Configure the fetcher to avoid v2, which allows fetching unadvertised
        # objects regardless of the value of uploadpack.allowAnySHA1InWant.
        s0.repo.config.set("protocol.version", "0", scope="local")
    
        # Configure s1 to succeed with direct fetch.
        s1.repo.config.set("uploadpack.allowAnySHA1InWant", "true",
                           scope="local")
    
        clone = install(
            str(path / "clone"),
            source="ssh://datalad-test:" + origin.repo.pathobj.as_posix())
    
        res = clone.get(["s0", "s1"], on_failure="ignore")
>       assert_result_count(res, 1,
                            action="install", type="dataset", status="error")
../datalad/distribution/tests/test_get.py:700: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
results = [{'action': 'install', 'contains': [PosixPath('/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3c...ported error']"), 'path': '/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s1', ...}]
n = 1, kwargs = {'action': 'install', 'status': 'error', 'type': 'dataset'}, count = 2
    def assert_result_count(results, n, **kwargs):
        """Verify specific number of results (matching criteria, if any)"""
        count = 0
        results = ensure_list(results)
        for r in results:
            if not len(kwargs):
                count += 1
            elif all(k in r and r[k] == v for k, v in kwargs.items()):
                count += 1
        if not n == count:
>           raise AssertionError(
                'Got {} instead of {} expected results matching\n{}\nInspected {} record(s):\n{}'.format(
                    count,
                    n,
                    _format_res(kwargs),
                    len(results),
                    _format_res(results)))
E           AssertionError: Got 2 instead of 1 expected results matching
E             {
E              "action": "install",
E              "status": "error",
E              "type": "dataset"
E             }
E           Inspected 2 record(s):
E             [
E              {
E               "action": "install",
E               "contains": [
E                "/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s0"
E               ],
E               "error_message": "Target commit c434f5a6 does not exist in the clone, and a fetch that commit from remote failed",
E               "exception": "ValueError(Target commit c434f5a6 does not exist in the clone, and a fetch that commit from remote failed)",
E               "exception_traceback": "[clone.py:clone_dataset:496,clone.py:_post_gitclone_processing_:583,clone.py:postclone_checkout_commit:763]",
E               "message": "Target commit c434f5a6 does not exist in the clone, and a fetch that commit from remote failed",
E               "path": "/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s0",
E               "source": {
E                "default_destpath": "s0",
E                "giturl": "ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/origin/s0",
E                "source": "ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/origin/s0",
E                "type": "giturl",
E                "version": null
E               },
E               "status": "error",
E               "type": "dataset"
E              },
E              {
E               "action": "install",
E               "contains": [
E                "/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s1"
E               ],
E               "message": [
E                "Failed to clone from any candidate source URL. Encountered errors per each url were:\n- %s",
E                "ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/origin/s1\n  CommandError: 'git -c diff.ignoreSubmodules=none clone --progress ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/origin/s1 /Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s1' failed with exitcode 128 [err: 'Cloning into '/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s1'...\nremote: Total 11 (delta 1), reused 0 (delta 0)        \nfatal: remote transport reported error']"
E               ],
E               "path": "/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/clone/s1",
E               "source": {
E                "default_destpath": "s1",
E                "giturl": "ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/origin/s1",
E                "source": "ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_test_get_subdataset_direct_fetch5k3cq4nk/origin/s1",
E                "type": "giturl",
E                "version": null
E               },
E               "status": "error",
E               "type": "dataset"
E              }
E             ]
../datalad/tests/utils_pytest.py:1520: AssertionError

```

### PR DESCRIPTION
**Pull request by bpoldrack**
`datalad sshrun` explicitly calls SSH with `log_output=False` which results in the use of `NoCapture` protocol with the runner. Meaning, stdout/stderr of SSH is written out anyway already. When SSH returns, `sshrun` tried to write both to its stdout/stderr. But: It could not possibly have anything to write. That would not be an issue in and of itself, but `sshrun` is not necessarily used directly. In particular it is called by `git` (due to `GIT_SSH_COMMAND=datalad sshrun`). This resulted in a problem when apparently `git` has closed the pipe to its ssh executable (`sshrun`) already and we tried to write to it (although we really didn't even have something to write).

This ultimately led to issue datalad#6599, where the actual `ssh ... git-upload-pack` execution succeeded and returned 0, but `datalad sshrun` itself produced a broken pipe error trying to write to stdout and hence returning non-zero.

It's not entirely clear when exactly this happens. When exactly the pipe is closed may be depend on git version as the failing builds are running 2.35.1 (MacOS on appveyor) whereas otherbuilds have either newer or older versions of git. In any case:
There can't be anything to write out to begin with, so don't even try.

Closes #6599
Closes #7078

### CODE REVIEW

**Review by mih — COMMENTED** [review]
I think a plain removal of these lines is not good. It is all but clear that there could not be any output to write from the code in this file. We are doomed to swallow something important at some point.

If this assertion hold (and needs to hold), an assertion should be in place.

But why not simple guard the write call, and turn it into a best-effort attempt? If a pipe is closed, it wont matter, it could not go anywhere anyways. But of it is open, and there is something, it will come out.

And this seems better than an assertion that does not hold, as it will leave the user with a crash.

WDYT?

**Comment by bpoldrack** [comment]
@mih : Well, I could do that obviously, but I don't see why. `log_output=False` is unconditional and it should be. A possibly captured output of the SSH call is currently piped through already. Why would we want to change that eventually in favor of a delayed output at the end (same content)? It sabotages any stdin/stdout communication with the caller for no obvious benefit.

**Comment by bpoldrack** [comment]
@mih : How about this https://github.com/datalad/datalad/pull/7072/commits/2231ba2d751ad0f5a65af8915b2314079cff706e ? (Will squash if you agree).
Thing is: If `out` and `err` exist, future debugging efforts can easily be set on the wrong track, assuming that there should be something in there, since the return value is stored (and even tried to use for writing).

**Comment by mih** [comment]
Added documentation is essential. Other than that I think the new implementation is as problematic re wrong assumptions about behavior as the one before. Your rational is based on assertions that are not in the code.

Anyways, no need to convince me.

**Comment by bpoldrack** [comment]
> Your rational is based on assertions that are not in the code.

I honestly don't understand what that assertion is. The now documented behavior of `log_output=False` is the implemented behavior of it and it's the entire point of the switch existing to begin with. I have no idea what "is not in the code". The switch says: "do not grab the output".

To me it's kinda the opposite. If I in 6 months time see `sshrun` implementing something like this:

```
out, err = ssh(...)

try:
   os.write(1, out)
except
   pass
```

I wonder how long it will take me to realize again, that with current implementation there can't be anything in that.

May be I'm not seeing something. I really don't know what it is.


WDYT, @datalad/developers ?

File: changelog.d/20221007_180414_benjaminpoldrack_fix_6599.md [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  Fixes https://github.com/datalad/datalad-next/issues/XXX via
+  https://github.com/datalad/datalad-next/pull/XXX (by @GITHUBHANDLE)
+-->
+<!--
+### Tests
+
+- Describe change, possibly reference closed/related issue/PR.
+  Fixes https://github.com/datalad/datalad-next/issues/XXX via
+  https://github.com/datalad/datalad-next/pull/XXX (by @GITHUBHANDLE)
+-->
```
Comment (yarikoptic) [inline changelog.d/20221007_180414_benjaminpoldrack_fix_6599.md:58]: remove all other stubs (even if scriv to remove them, why bother carrying in the diffs etc)?

**Review by yarikoptic — CHANGES_REQUESTED** [review]
my thinking about it -- I think we better `assert` the assumptions of the code especially if there was prior code thinking otherwise

**Comment by yarikoptic** [comment]
Thank you @bpoldrack - let's proceed!

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.7`](https://github.com/datalad/datalad/releases/tag/0.17.7)
